In [2]:
%matplotlib inline
from mxnet import np,npx
from matplotlib_inline import backend_inline

# kid_ages = [2, 7, 5, 6, 3]

# max = ""
# max = max(kid_ages)
# print(max)

# print(type(npx.num_gpus()))

# fair_probs = [1.0 / 6] * 6 
# print(fair_probs)
# np.random.multinomial(1, fair_probs)
# np.random.multinomial(100, fair_probs).astype(np.float32)

npx.set_np()


# x = np.arange(0,12,0.1)
# x


# print(x)
# print(x.shape)
# x.size


# X = x.reshape(30, 4)
# print(X)


# X
# x = np.zeros((2, 3, 4))
# x
x = np.random.normal(0, 1, size=(4, 3))
print(x.shape)
print(x)
# x = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
# x
# x = np.array([1, 2, 4, 8])
# x = np.exp(x)
a = np.arange(3)
print(np.matmul(x,a.T))
 
##* 和 matmul区别
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print('++++++++++')
print(A)
print(B)
print(A*B)
print(np.matmul(A,B))
print('++++++++++')
print(a.T)
print('-------------')
print(x*a.T)
# b = np.arange(3).reshape(1,3)
# a*b
# X[-1],X[1:3]
# A = X.asnumpy()
# B = np.array(A)
# type(A), type(B)
# X = np.arange(24).reshape(2, 3, 4)
# X
# A = np.arange(20).reshape(5, 4)
# B = A.copy()  # 通过分配新内存，将A的一个副本分配给B
# A
# x = np.arange(0, 3, 0.1)
# x

(4, 3)
[[-0.5459446  -1.771029   -2.3556297 ]
 [-0.45138445  0.5414402   0.57938355]
 [ 2.6785066  -1.856082    1.2546344 ]
 [-1.9768796  -0.54877394 -0.20801921]]
[-6.4822884  1.7002072  0.6531868 -0.9648124]
++++++++++
[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 5. 12.]
 [21. 32.]]
[[19. 22.]
 [43. 50.]]
++++++++++
[0. 1. 2.]
-------------
[[-0.         -1.771029   -4.7112594 ]
 [-0.          0.5414402   1.1587671 ]
 [ 0.         -1.856082    2.5092688 ]
 [-0.         -0.54877394 -0.41603842]]
