In [3]:
%matplotlib inline
from mxnet import np,npx
from matplotlib_inline import backend_inline


# kid_ages = [2, 7, 5, 6, 3]

# max = ""
# max = max(kid_ages)
# print(max)

# print(type(npx.num_gpus()))

fair_probs = [1.0 / 6] * 6 
print(fair_probs)
b = np.random.multinomial(1, fair_probs, size=2)
b2 = np.random.multinomial(100, fair_probs, size=1).astype(np.float32)
print("*******")
print(b)
print("*******")
print(b2)
print("*******")
npx.set_np()

x = np.arange(0,12,0.1)
print(x)
print(x.shape)
# x.size
X = x.reshape(30, 4)
print(X)

# x = np.zeros((2, 3, 4))
x = np.random.normal(0, 1, size=(4, 3))
print(x.shape)
print(x)
# x = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
# x = np.array([1, 2, 4, 8])
# x = np.exp(x)
a = np.arange(3)
a = np.array([1, 1, 1])
print(a)
print('===============0.1156979')
print(np.matmul(x,a.T))
##* 和 matmul区别
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print('++++++++++')
print(A)
print(B)
print(A*B)
print(np.matmul(A,B))
print('++++++++++')
print(a.T)
print('-------------')
print(x*a.T)
# b = np.arange(3).reshape(1,3)
# a*b
# X[-1],X[1:3]
# A = X.asnumpy()
# B = np.array(A)
# type(A), type(B)
# X = np.arange(24).reshape(2, 3, 4)
# X
# A = np.arange(20).reshape(5, 4)
# B = A.copy()  # 通过分配新内存，将A的一个副本分配给B
# A
# x = np.arange(0, 3, 0.1)
# x

X = np.random.uniform(size=(2, 4))
print(X)

import numpy as np

# Replace this with your actual data
your_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Calculate the mean
mean_value = np.mean(your_array)

# Print the result
print(mean_value)

[0.16666666666666666, 0.16666666666666666, 0.16666666666666666, 0.16666666666666666, 0.16666666666666666, 0.16666666666666666]
*******
[[0 0 1 0 0 0]
 [0 0 1 0 0 0]]
*******
[[15. 16. 21. 13. 13. 22.]]
*******
[ 0.          0.1         0.2         0.3         0.4         0.5
  0.6         0.7         0.8         0.90000004  1.          1.1
  1.2         1.3000001   1.4         1.5         1.6         1.7
  1.8000001   1.9         2.          2.1000001   2.2         2.3
  2.4         2.5         2.6000001   2.7         2.8         2.9
  3.          3.1000001   3.2         3.3         3.4         3.5
  3.6000001   3.7         3.8         3.9         4.          4.1
  4.2000003   4.3         4.4         4.5         4.6         4.7000003
  4.8         4.9         5.          5.1         5.2000003   5.3
  5.4         5.5         5.6         5.7000003   5.8         5.9
  6.          6.1         6.2000003   6.3         6.4         6.5
  6.6         6.7000003   6.8         6.9         7.      