In [1]:
from mxnet import autograd, np, npx
from mxnet.gluon import nn

npx.set_np()

def corr2d(X, K):  #@save
    """计算二维互相关运算"""
    h, w = K.shape
    print(K.shape)
    print(X.shape)
    
    Y = np.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))
    print(Y)
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            print(i)
            print(j)
            print(X[i:i + h, j:j + w] * K)
            Y[i, j] = (X[i:i + h, j:j + w] * K).sum()
            print(Y)
    return Y

X = np.array([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
K = np.array([[0.0, 1.0], [2.0, 3.0]])
corr2d(X, K)

(2, 2)
(3, 3)
[[0. 0.]
 [0. 0.]]
0
0
[[ 0.  1.]
 [ 6. 12.]]
[[19.  0.]
 [ 0.  0.]]
0
1
[[ 0.  2.]
 [ 8. 15.]]
[[19. 25.]
 [ 0.  0.]]
1
0
[[ 0.  4.]
 [12. 21.]]
[[19. 25.]
 [37.  0.]]
1
1
[[ 0.  5.]
 [14. 24.]]
[[19. 25.]
 [37. 43.]]


array([[19., 25.],
       [37., 43.]])