In [27]:
from mxnet import np, npx
from mxnet.gluon import nn


npx.set_np()

def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = np.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i: i + p_h, j: j + p_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i: i + p_h, j: j + p_w].mean()
            elif mode == 'min':
                Y[i, j] = X[i: i + p_h, j: j + p_w].min()
    return Y

X = np.array([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
pool2d(X, (2, 2))

pool2d(X, (2, 2), 'max')


X = np.arange(16, dtype=np.float32).reshape((1, 1, 4, 4))
print(X)

pool2d = nn.MaxPool2D(2)
# 由于汇聚层中没有参数，所以不需要调用初始化函数
pool2d(X)
print(X)

X = np.concatenate((X, X + 1), 1)
pool2d = nn.MaxPool2D(3, padding=1, strides=2)
pool2d(X)




[[[[ 0.  1.  2.  3.]
   [ 4.  5.  6.  7.]
   [ 8.  9. 10. 11.]
   [12. 13. 14. 15.]]]]
[[[[ 0.  1.  2.  3.]
   [ 4.  5.  6.  7.]
   [ 8.  9. 10. 11.]
   [12. 13. 14. 15.]]]]


array([[[[ 5.,  7.],
         [13., 15.]],

        [[ 6.,  8.],
         [14., 16.]]]])