In [13]:
%time
import numpy as np
a = np.random.rand(2,3,4,5)
print(a)
print(a.shape)
print(np.mean(a,axis=(0,2,3),keepdims=True))

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 11 µs
[[[[0.93394445 0.99095746 0.22220857 0.89633205 0.47564966]
   [0.53648445 0.23966359 0.6789729  0.75861518 0.60921138]
   [0.75776435 0.2145834  0.65806226 0.01943604 0.40896676]
   [0.50371749 0.14172416 0.82718747 0.01918467 0.96754219]]

  [[0.96861796 0.95784118 0.84509847 0.3275766  0.61094262]
   [0.83096567 0.54866214 0.49644883 0.46663221 0.2521366 ]
   [0.37401798 0.86169546 0.52842166 0.43107598 0.16042167]
   [0.96927912 0.31819652 0.17899676 0.50340509 0.73874164]]

  [[0.90869273 0.26389896 0.09569904 0.86569168 0.97634868]
   [0.58471243 0.46429352 0.42113314 0.02955906 0.90393392]
   [0.4776521  0.72743923 0.07457612 0.81311448 0.66779293]
   [0.20685262 0.35865719 0.2656492  0.84496193 0.30056   ]]]


 [[[0.365233   0.86011038 0.00246233 0.32340989 0.37859738]
   [0.01767153 0.4334216  0.36493799 0.22634843 0.57682129]
   [0.86989072 0.64320351 0.57307328 0.10385121 0.15200372]
   [0.40050594 0.29209255 0.50